#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /inicio
    controller: App\Controller\HomeController::index

#animales:
#    path: /animales/{nombre}
#    controller: App\Controller\HomeController::animales
#    defaults: { nombre: 'Pablo Moras Hernando'}

animales:
    path: /animales/{nombre}/{numero}
    controller: App\Controller\HomeController::animales
    defaults: { nombre: 'Oso', numero: '43'}
    methods: [GET] #[GET,POST]
    requirements:
      nombre: '[a-zA-Z ]+'
      numero: '[0-9]+'


#   > parametros opcionales
#animales:
#    path: /animales/{nombre?}
#    controller: App\Controller\HomeController::animales
#    defaults: { nombre: 'AbraKadabra'}

redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir

redireccionado:
    path: /redireccionado
    controller: App\Controller\HomeController::redireccionado

animal_index:
    path: /animal/index
    controller: App\Controller\AnimalController::index

animal_save:
    path: /animal/save
    controller: App\Controller\AnimalController::save
    methods: [POST]

animal_detail:
    path: /animal/{id}
    controller: App\Controller\AnimalController::animal

animal_update:
    path: /animal/update/{id}
    controller: App\Controller\AnimalController::update

animal_delete:
    path: /animal/delete/{id}
    controller: App\Controller\AnimalController::delete

animal_create:
    path: /crear-animal
    controller: App\Controller\AnimalController::crearAnimal

validar_email:
    path: /validar-email/{email}
    controller: App\Controller\AnimalController::validarEmail
